logging:
  level:
    root:
      ${LOG_LEVEL:info}
server:
  port: 8082
  servlet:
    context-path: /oss/api/
spring:
  http:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
      force-request: true
      force-response: true
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: ALWAYS
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
