spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 10
      pool-name: accountHikariCP

    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database
    password:
    username:

  jpa:
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: false
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        use_sql_comments: true
    show-sql: ${SHOW_SQL:false}
    open-in-view: false
